###

GET http://localhost:3000/Promocion

###
PUT  http://localhost:3000/Bodega/1
Content-Type: application/json
 
{
  "nombre": "khsdjsdhj",
  "ubicacion": "nuevo",
  "estado": "Activo"
}


###
POST http://localhost:3000/Configuracion
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="nombreNegocio"

Nombre de Mi Negocio
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="logoLocal"; filename="3fa3d6b5dc400bb1dsdbfb051ce48fc4afb.jpg"
Content-Type: image/jpeg

(binary data of your image file)
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="ruc"

12345678901
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="telefonos"

123-456-7890
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="correo"

correo@miempresa.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="direccion"

Calle Principal #123
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="estado"

Activo
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="usuarioModificacion"

NombreUsuario
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="tipoOperacion"

INSERT
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###

PUT  http://localhost:3000/Talla/Activar/2
Content-Type: application/json

{
 

}

### Prueba de acceso al recurso protegido con un usuario "Admin"
GET http://localhost:3000/registerUser
Authorization: Bearer <Admin>

####
POST http://localhost:3000/registerUser
Content-Type: application/json

{
  "Nombres": "Omar",
  "Apellidos": "Navas",
  "LoginUsuario": "User",
  "LoginClave": "12345",
  "IdRol": 1,
 "Estado":"Activo"
}


###
POST http://localhost:3000/Login
Content-Type: application/json


{
 
  "user": "User",
  "password": "12345"


}



###
DELETE http://localhost:3000/Categoria/1
Content-Type: application/json


###
PUT  http://localhost:3000/Producto/1
Content-Type: application/json

{
  "nombre": "s",
  "descripcion":"hola",
  "estado": "true",
  "id_categoria":1
}




###
GET http://localhost:3000/Marcas

####
POST http://localhost:3000/Tallas
Content-Type: application/json

{
  "Nombre": "dfdfd",
  "estado": "true"
}

###
DELETE http://localhost:3000/tallas/3
Content-Type: application/json


###
PUT  http://localhost:3000/tallas/6
Content-Type: application/json

{
 "nombre": "hola",
  "estado": "0"
}