
GET http://localhost:3000/Categoria
###
POST http://localhost:3000/Categoria
Content-Type: application/json


{
  "nombre": "hola"

}
### Prueba de acceso al recurso protegido con un usuario "Admin"
GET http://localhost:3000/Categorias
Authorization: Bearer <Admin>

####
POST http://localhost:3000/registerUser
Content-Type: application/json


{
  "Nombres": "jh",
  "Apellidos": "sd",
  "LoginUsuario": "User",
  "LoginClave": "12345",
  "IdRol": 1
}


###
POST http://localhost:3000/Login
Content-Type: application/json


{
 
  "user": "User",
  "password": "12345"


}



###
DELETE http://localhost:3000/Categoria/1
Content-Type: application/json


###
PUT  http://localhost:3000/Producto/1
Content-Type: application/json

{
  "nombre": "s",
  "descripcion":"hola",
  "estado": "true",
  "id_categoria":1
}




###
GET http://localhost:3000/Marcas

####
POST http://localhost:3000/Tallas
Content-Type: application/json

{
  "Nombre": "dfdfd",
  "estado": "true"
}

###
DELETE http://localhost:3000/tallas/3
Content-Type: application/json


###
PUT  http://localhost:3000/tallas/6
Content-Type: application/json

{
 "nombre": "hola",
  "estado": "0"
}